### ISSUE TITLE
Did `Document.SaveMode.SaveTo` Just wipe my entire ~/Documents folder?!?

### ISSUE THREAD

**Issue by smlparry** [BohemianCoding/SketchAPI#248]
Im a little bit taken aback right now, I am building a Sketch plugin and am playing around with saving out a document. I ran this code: 

```
const document = Document.getSelectedDocument();
const newDoc = document.save("~/Documents/", {
    saveMode: Document.SaveMode.SaveTo
});
```

Trying to see what would happen if I didnt specify a file name, and it seems to have just wiped my entire folder??? What does this method actually do? The files are not in my trash either

![screen shot 2018-09-18 at 15 06 01](https://user-images.githubusercontent.com/7920702/45665522-a2eeb500-bb54-11e8-8ad9-f4eef67b9403.png)

Any help would be greatly appreciated as I would like to recover those files

**Comment by bomberstudios** [comment]
Hi Samuel.

I'm heartbroken to read this message. Apparently the method we're using under the hood (AppKit's own `[NSDocument saveToURL:ofType:forSaveOperation::completionHandler:]`) does not have any sort of safety check, and will happily replace a folder with a file if you tell it to do that.

We'll immediately add a check on our side before calling that method, so that this doesn't ever happen again.

As for recovering your files: if you don't have a backup copy on iCloud or Time Machine, a file recovery tool like [PhotoRec](https://www.cgsecurity.org/wiki/PhotoRec) or [Disk Drill](https://www.cleverfiles.com/mac-data-recovery.html) is the best choice.

Again, I'm really sorry that you found out about this the hard way. If there's anything I can do to help you, please get in touch directly with me at ale@sketchapp.com and I'll do my best to assist you.
