### ISSUE TITLE
Code Style: need lint rules

### ISSUE THREAD

**Issue by plrthink** [BohemianCoding/SketchAPI#35]
Perhaps we need some lint rules to ensure the code style?

**Comment by mossyblog** [comment]
- Keep in mind this is taking a dependency on code outside the ES6 / Node modules. Therefore the entire ruleset will need fair amount of setup work to overcome expectations. Already I'm seeing the `globals` having "ignore" rules just for `no-undef` same goes with `new-cap`

- These rules will need to be transportable to the community as well to ensure every ones boats are able to rise with the same tide (as in the `.eslintrc.js` will need to also be versioned).

- One would need to also ensure a healthy "setup" wiki is kept up to date in order to ensure everyone who contributes or builds standard "plugins" can achieve parity without frustration.

**Comment by mossyblog** [comment]
I've implemented eslint using `Standard` as the chosen format / guidelines. #36 has the current working code up to parity with 0 issues.

**Comment by mathieudutour** [comment]
fixed in #68
