### ISSUE TITLE
Support multiline input in UI.getInputFromUser

### ISSUE THREAD

**Issue by bomberstudios** [BohemianCoding/SketchAPI#450]
It would be great for this plugin I wrote, where a single line input is clearly not cutting it : )

<img width="532" alt="Screen Shot 2019-04-04 at 10 34 44" src="https://user-images.githubusercontent.com/3832/55552413-92132480-56dd-11e9-8f49-d85d06315901.png">

**Comment by WCByrne** [comment]
Tangential to this, it would awesome to have some sort of UI builder that could contain multiple components. That would allow plugins to build say a native looking settings UI with minimal effort.

**Comment by markhorgan** [comment]
There is one - it's called XCode :). Create your UI in XCode and use [nib-loader](https://github.com/skpm/nib-loader) to load it.

**Comment by WCByrne** [comment]
Well, there is always that but I wouldn't call that "minimal effort". In the middle of rebuilding my plugin I have to say I'm very happy in my new world with no ObjC framework. 😄

**Comment by markhorgan** [comment]
It's fairly minimal effort. You just create a xib file inside an empty framework and nib-loader compiles it to a nib file that's part of your plugin - the plugin doesn't contain a framework.

**Comment by robintindale** [comment]
Another contender for the "minimal effort" awards - a webview. 

Looks pretty native with `<button>` and `<input>` fields, and is easy to build if you're familiar with web technologies (e.g. I've never used Xcode UI stuff, so it would be friction for me personally)

**Comment by mathieudutour** [comment]
I agree with everything said here 😆 

- A webview would be my go-to solution for any complex UI
- For a UI that's not too complex, a xib is really nice, skpm makes it fairly smooth.
- A UI builder would be nice for sure but ultimately, it would end up generating something really similar to a xib

But back to the original point, a multiline input should be easy to add

**Comment by WCByrne** [comment]
Haha, this conversation took off 😄 

FWIW, my use case that triggered this idea was for the plugin reloader I built. There were two things:

1. There are 2 steps to set it up now, one to get the plugin ID and another to get any data you want to send to the plugin when it is reloaded. Right now that is done with 2 input prompts shown one after the other. Ideally it would be one but it was too cumbersome to built that out myself for and otherwise very simple plugin.

2. I wanted to make notifying the reloaded plugin an option but with no checkbox I decided to just always do it. Could have used a text field but 😒 

I guess the point is, there is a ton a plugin can do without a UI (I assume most plugins fall into this category). If your focus is on manipulating content in a document it feels like a big leap just to add a few options in a settings UI that can customize how the real work is performed.

Maybe this is something that would be better solved by a standalone package but what I was imagining was something like:
```
# Get settings for a plugin that prefixes objects for you (Just an example)
UI.prompt(title, [
   {
        title: "Prefix",
        type: type: UI.INPUT_TYPE.text,
   },
   {
        title: "Symbols",
        type: UI.INPUT_TYPE.checkbox,
        checked: true
   },
   {
        title: "Layer Styles",
        type: UI.INPUT_TYPE.checkbox,
        checked: false
   },
   ...
], result => {
  const prefix = result[0];
  const prefixSymbols = result[1];
  const prefixLayerStyles = result[2];
  // Save to settings
});
```

**Comment by mathieudutour** [comment]
Ah something I should have mentioned is that we want to limit as much as possible the API that does not require Sketch integration.
In a perfect world, SketchAPI would only touch the Sketch internals. Every other library that requires Cocoa would be separate projects (like `skpm/fs`, `skpm/dialog`, `sketch-module-web-view`, etc.) which could still be developed by BC but also by the community (a lot easier to contribute since it doesn't require internal knowledge).

The API you are suggesting could totally be a separate library!
