### ISSUE TITLE
Always 0 when evaluate Objective-C Enum value of Sketch on MacOS10.15Beta

### ISSUE THREAD

**Issue by colorgmi** [BohemianCoding/SketchAPI#558]
Hello, I have found a problem; but I don't know why.
 
from MacOS10.15Beta,
SketchApp Run Script:
```
const r = NSUTF8StringEncoding

console.log(r)
```
The result always 0, no matter what Objective-C Enum value here;

But MacOS10.14, MacOS10.13, is OK;
when this case, value is 4, 4 is correct from documentation of Xcode.

So I have to manually replace all Objective-C enum value to integer,
in order to make plugin works on MacOS10.15Beta; that's not so good.

**Comment by mathieudutour** [comment]
Indeed, that's a weird bug. We are looking into it

**Comment by huw** [comment]
To clarify, this is affecting _all_ Objective-C enums, which breaks almost every plugin. **You can't ship for 10.15 without fixing this.** It's still broken in the latest Catalina beta.

I assume it's because Mocha isn't setting the value properly, so it's defaulting to whatever the NSInteger default is (0). I tried to work with that codebase, but ran into a lot of compiler errors (I assume you're building your own internally).

The code in question is probably https://github.com/logancollins/Mocha/blob/ccc18bf89a044f78bb332a8b8854f2d779e1ce57/Mocha/BridgeSupport/MOBridgeSupportParser.m#L145. It could be to do with [recent, underdocumented API changes to NSNumber](https://developer.apple.com/documentation/foundation/nsnumber?changes=latest_major&language=objc).

**Comment by mathieudutour** [comment]
It’s not no. It was because of a typo in CocoaScript: https://github.com/ccgus/CocoaScript/pull/63

It will be fixed in an upcoming version of Sketch but keeping it opened for people to be able to see it

**Comment by huw** [comment]
Huh! Thanks for solving it — do you think this'll land with Sketch 56?

**Comment by mathieudutour** [comment]
I don’t think so, Sketch 56 has been code freezed already and we still have to fix our infra for 10.15. But 57?will follow shortly after!

**Comment by huw** [comment]
I gave this a go on Sketch 57 Beta 1 — it looks like the same problem is still happening. I assume I should wait for Beta 2 or 3?

**Comment by hadihallak** [comment]
Same here. for example, webview plugins still appear borderless (no window or window controls)

**Comment by mathieudutour** [comment]
I just merged the fix so yeah, next beta :)

**Comment by robintindale** [comment]
Just testing this on the latest prod / latest beta, I'm seeing windows and controls, but close is not working. The window is staying open despite clicking the close control, and if I try and close the window from within the webview with `this.window.close`, it says `this.window` is `null`. Verified this with sketch-dev-tools and a window from our own plugin

**Comment by huw** [comment]
Oh, just to confirm — this isn’t fixed in Sketch 57. Looks like they didn’t do a beta 2.

**Comment by mathieudutour** [comment]
I just updated the dependencies of `sketch-dev-tools` and it seems to work fine

**Comment by robintindale** [comment]
Hmm I've updated my `sketch-module-web-view` and get the same behavior. Will create a new issue over there 👍
