### ISSUE TITLE
setting the frame of a Layer makes Sketch crash

### ISSUE THREAD

**Issue by everdrone** [BohemianCoding/SketchAPI#80]
```
/* ... */
var copy = someLayer.duplicate();
var rect = new sketch.Rectangle(0, 0, 100, 200);
copy.frame = rect;
```

**Comment by mathieudutour** [comment]
be careful, `new sketch.Rectangle()` doesn't do what you expect. What you want is
```js
var Rectangle = sketch.Rectangle
var rect = new Rectangle(0, 0, 100, 200)
```

**Comment by everdrone** [comment]
still crashing

here is the code:
```javascript
var sketch = context.api();

var document = sketch.selectedDocument;
var selection = document.selectedLayers;
var page = document.selectedPage;

if (selection.isEmpty) {
  sketch.message('empty');
} else {
  var original = selection.nativeLayers[0];
  var copy = original.duplicate();
  
  var Rectangle = sketch.Rectangle;
  var rect = new Rectangle(0, 0, 100, 200);
  copy.frame = rect;
}
```
ran from `sketch-dev-tools`' playground

**Comment by mathieudutour** [comment]
you are mixing wrapped objects and native objects. `copy` is a native sketch layer so its frame expects a `CGRect`: `copy.frame = rect.asCGRect();`

This selection is a bit messy since there is no way to access a wrapped object from it :/ Hopefully it will be easier with the new API: https://github.com/BohemianCoding/SketchAPI/blob/feature/15747/docs/Selection.md

**Comment by everdrone** [comment]
still crashing.

All i want to achieve is duplicate the selected layer and translate/resize it.

is there an easy way to do it with the current API?

**Comment by nichenqin** [comment]
@everdrone try this:
```javascript
copy.frame().setX_(300);
copy.frame().setY_(300);
copy.frame().setHeight_(300);
copy.frame().setWidth_(300);
```

**Comment by everdrone** [comment]
it works! thanks @nichenqin
