### ISSUE TITLE
Can I use the new API in old sketch version?

### ISSUE THREAD

**Issue by nichenqin** [BohemianCoding/SketchAPI#88]
It seems that the new API is absolutely different from the old one, can I just get the new API in old sketch version like release 48.2?
If not, does it mean that we have to rewrite our plugin and keep both two versions of plugin to adapt new release 49 and the older ones?

**Comment by mathieudutour** [comment]
No you can't the new API in an old sketch version (since we can't ship code to an old version).
But the old API will continue to work so you don't need to rewrite your existing plugin.

The adoption rate of new releases is pretty good tho so a month or two after the Sketch 49 release, you should be able to to target it only (if you want to)
